
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class TP_II extends javax.swing.JFrame {

    /**
     * Creates new form TP
     */
    public TP_II() {
        initComponents();
        //Para inhabilitar los campos de texto al iniciarse el formulario.
        jTFNombre.setEnabled(false);
        jTFApellido.setEnabled(false);
        jTFTelefono.setEnabled(false);
        jSEdad.setEnabled(false);
        jCBSexo.setEnabled(false);    
    }
        //Inicializar las variables fuera cualquier clase.
        private int totalAlumnos = 0;
        private int mascEnfermeria = 0, femEnfermeria = 0;
        private int mascNutricion = 0, femNutricion = 0;
        private int mascFisioterapia = 0, femFisioterapia = 0;
        private int mascInformatica = 0, femInformatica = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGCarreras = new javax.swing.ButtonGroup();
        jPCarreras = new javax.swing.JPanel();
        jRBEnfermeria = new javax.swing.JRadioButton();
        jRBNutricion = new javax.swing.JRadioButton();
        jRBFisioterapia = new javax.swing.JRadioButton();
        jRBInformatica = new javax.swing.JRadioButton();
        jPRegistrar = new javax.swing.JPanel();
        jLBNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLBApellido = new javax.swing.JLabel();
        jTFApellido = new javax.swing.JTextField();
        jLBTelefono = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jLEdad = new javax.swing.JLabel();
        jSEdad = new javax.swing.JSpinner();
        jLSexo = new javax.swing.JLabel();
        jCBSexo = new javax.swing.JComboBox<>();
        jBInscribir = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jBVaciar = new javax.swing.JButton();
        jPDetalleInscripcion = new javax.swing.JPanel();
        jCBEnfermeria = new javax.swing.JComboBox<>();
        jCBFisioterapia = new javax.swing.JComboBox<>();
        jSPNutricion = new javax.swing.JScrollPane();
        jLNutricion = new javax.swing.JList<>();
        jSPInformatica = new javax.swing.JScrollPane();
        jLInformatica = new javax.swing.JList<>();
        jPCantidad = new javax.swing.JPanel();
        jLBEnfermeria = new javax.swing.JLabel();
        jLBFisioterapia = new javax.swing.JLabel();
        jLBInformatica = new javax.swing.JLabel();
        jLEnferFem = new javax.swing.JLabel();
        jLNutriFem = new javax.swing.JLabel();
        jLFisioFem = new javax.swing.JLabel();
        jLInfoFem = new javax.swing.JLabel();
        jLFisioMasc = new javax.swing.JLabel();
        jLInfoMasc = new javax.swing.JLabel();
        jLEnferMasc = new javax.swing.JLabel();
        jLNutriMasc = new javax.swing.JLabel();
        jLBNutricion = new javax.swing.JLabel();
        jSTotal = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPCarreras.setBorder(javax.swing.BorderFactory.createTitledBorder(" Carreras"));

        bGCarreras.add(jRBEnfermeria);
        jRBEnfermeria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRBEnfermeria.setText("Lic. en Enfermería");
        jRBEnfermeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEnfermeriaActionPerformed(evt);
            }
        });

        bGCarreras.add(jRBNutricion);
        jRBNutricion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRBNutricion.setText("Lic. en Nutrición");
        jRBNutricion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNutricionActionPerformed(evt);
            }
        });

        bGCarreras.add(jRBFisioterapia);
        jRBFisioterapia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRBFisioterapia.setText("Fisioterapia y Kinesiología");
        jRBFisioterapia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFisioterapiaActionPerformed(evt);
            }
        });

        bGCarreras.add(jRBInformatica);
        jRBInformatica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRBInformatica.setText("Lic. en Informática");
        jRBInformatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBInformaticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCarrerasLayout = new javax.swing.GroupLayout(jPCarreras);
        jPCarreras.setLayout(jPCarrerasLayout);
        jPCarrerasLayout.setHorizontalGroup(
            jPCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarrerasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBEnfermeria)
                    .addComponent(jRBNutricion)
                    .addComponent(jRBFisioterapia)
                    .addComponent(jRBInformatica))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPCarrerasLayout.setVerticalGroup(
            jPCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarrerasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBEnfermeria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBNutricion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBFisioterapia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBInformatica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar alumnos"));

        jLBNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLBNombre.setText("Nombre:");

        jLBApellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLBApellido.setText("Apellido:");

        jLBTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLBTelefono.setText("Teléfono:");

        jLEdad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLEdad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLEdad.setText("Edad:");

        jSEdad.setModel(new javax.swing.SpinnerNumberModel(18, 18, 150, 1));
        jSEdad.setToolTipText("");

        jLSexo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLSexo.setText("Sexo:");

        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "M", "F" }));
        jCBSexo.setToolTipText("");

        javax.swing.GroupLayout jPRegistrarLayout = new javax.swing.GroupLayout(jPRegistrar);
        jPRegistrar.setLayout(jPRegistrarLayout);
        jPRegistrarLayout.setHorizontalGroup(
            jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSexo)
                    .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLBTelefono)
                        .addComponent(jLEdad, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLBNombre)
                    .addComponent(jLBApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFApellido)
                    .addComponent(jTFNombre)
                    .addComponent(jTFTelefono)
                    .addComponent(jSEdad)
                    .addComponent(jCBSexo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 389, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPRegistrarLayout.setVerticalGroup(
            jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistrarLayout.createSequentialGroup()
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSexo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBInscribir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBInscribir.setText("Inscribir Alumno");
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        jBLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBLimpiar.setText("Limpiar Datos de Matriculación");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jBVaciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBVaciar.setText("Vaciar Detalle de Inscripción");
        jBVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVaciarActionPerformed(evt);
            }
        });

        jPDetalleInscripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Inscripción"));

        jCBEnfermeria.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumnos de Enfermería"));

        jCBFisioterapia.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumnos de Fisioterapia"));

        jLNutricion.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumnos de Nutrición"));
        jSPNutricion.setViewportView(jLNutricion);

        jLInformatica.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumnos de Informática"));
        jSPInformatica.setViewportView(jLInformatica);

        javax.swing.GroupLayout jPDetalleInscripcionLayout = new javax.swing.GroupLayout(jPDetalleInscripcion);
        jPDetalleInscripcion.setLayout(jPDetalleInscripcionLayout);
        jPDetalleInscripcionLayout.setHorizontalGroup(
            jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetalleInscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBEnfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBFisioterapia, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jSPNutricion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSPInformatica, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPDetalleInscripcionLayout.setVerticalGroup(
            jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetalleInscripcionLayout.createSequentialGroup()
                .addGroup(jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSPInformatica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSPNutricion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPDetalleInscripcionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBEnfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jCBFisioterapia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Alumnos por Carrera:"));

        jLBEnfermeria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBEnfermeria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLBEnfermeria.setText("Enfermería:");

        jLBFisioterapia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBFisioterapia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLBFisioterapia.setText("Fisioterapia:");

        jLBInformatica.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBInformatica.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLBInformatica.setText("Informática:");

        jLEnferFem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEnferFem.setText("0");
        jLEnferFem.setBorder(javax.swing.BorderFactory.createTitledBorder("Femenino"));

        jLNutriFem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNutriFem.setText("0");
        jLNutriFem.setBorder(javax.swing.BorderFactory.createTitledBorder("Femenino"));

        jLFisioFem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFisioFem.setText("0");
        jLFisioFem.setBorder(javax.swing.BorderFactory.createTitledBorder("Femenino"));

        jLInfoFem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInfoFem.setText("0");
        jLInfoFem.setBorder(javax.swing.BorderFactory.createTitledBorder("Femenino"));

        jLFisioMasc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFisioMasc.setText("0");
        jLFisioMasc.setBorder(javax.swing.BorderFactory.createTitledBorder("Masculino"));

        jLInfoMasc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInfoMasc.setText("0");
        jLInfoMasc.setBorder(javax.swing.BorderFactory.createTitledBorder("Masculino"));

        jLEnferMasc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEnferMasc.setText("0");
        jLEnferMasc.setBorder(javax.swing.BorderFactory.createTitledBorder("Masculino"));

        jLNutriMasc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNutriMasc.setText("0");
        jLNutriMasc.setBorder(javax.swing.BorderFactory.createTitledBorder("Masculino"));

        jLBNutricion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLBNutricion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLBNutricion.setText("Nutrición:");

        javax.swing.GroupLayout jPCantidadLayout = new javax.swing.GroupLayout(jPCantidad);
        jPCantidad.setLayout(jPCantidadLayout);
        jPCantidadLayout.setHorizontalGroup(
            jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCantidadLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLBEnfermeria)
                    .addComponent(jLBNutricion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEnferFem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNutriFem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPCantidadLayout.createSequentialGroup()
                        .addComponent(jLNutriMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLBInformatica))
                    .addGroup(jPCantidadLayout.createSequentialGroup()
                        .addComponent(jLEnferMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLBFisioterapia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCantidadLayout.createSequentialGroup()
                        .addComponent(jLFisioFem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLFisioMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCantidadLayout.createSequentialGroup()
                        .addComponent(jLInfoFem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLInfoMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCantidadLayout.setVerticalGroup(
            jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCantidadLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEnferFem)
                    .addComponent(jLEnferMasc)
                    .addComponent(jLBEnfermeria)
                    .addComponent(jLBFisioterapia)
                    .addComponent(jLFisioFem)
                    .addComponent(jLFisioMasc))
                .addGap(8, 8, 8)
                .addGroup(jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNutriFem)
                    .addGroup(jPCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBInformatica)
                        .addComponent(jLInfoFem)
                        .addComponent(jLInfoMasc)
                        .addComponent(jLNutriMasc)
                        .addComponent(jLBNutricion)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jSTotal.setMajorTickSpacing(10);
        jSTotal.setMinorTickSpacing(2);
        jSTotal.setPaintLabels(true);
        jSTotal.setPaintTicks(true);
        jSTotal.setToolTipText("");
        jSTotal.setValue(0);
        jSTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total de Alumnos Insciptos"));
        jSTotal.setExtent(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPDetalleInscripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBInscribir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBLimpiar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jBLimpiar)
                    .addComponent(jBVaciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPDetalleInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Habilitar los campos de texto al seleccionar una de las opciones de carreras.
    private void jRBEnfermeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEnfermeriaActionPerformed
        jTFNombre.setEnabled(true);
        jTFApellido.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jSEdad.setEnabled(true);
        jCBSexo.setEnabled(true);
        jTFNombre.requestFocusInWindow();
    }//GEN-LAST:event_jRBEnfermeriaActionPerformed

    private void jRBNutricionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNutricionActionPerformed
        jTFNombre.setEnabled(true);
        jTFApellido.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jSEdad.setEnabled(true);
        jCBSexo.setEnabled(true);
        jTFNombre.requestFocusInWindow();
    }//GEN-LAST:event_jRBNutricionActionPerformed

    private void jRBFisioterapiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFisioterapiaActionPerformed
        jTFNombre.setEnabled(true);
        jTFApellido.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jSEdad.setEnabled(true);
        jCBSexo.setEnabled(true);
        jTFNombre.requestFocusInWindow();
    }//GEN-LAST:event_jRBFisioterapiaActionPerformed

    private void jRBInformaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBInformaticaActionPerformed
        jTFNombre.setEnabled(true);
        jTFApellido.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jSEdad.setEnabled(true);
        jCBSexo.setEnabled(true);
        jTFNombre.requestFocusInWindow();
    }//GEN-LAST:event_jRBInformaticaActionPerformed

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        //Validación de los datos ingresados.
        if(jTFNombre.getText().length()==0 || jTFApellido.getText().length()==0){
            JOptionPane.showMessageDialog(  this, "Los campos Nombre y Apellido no pueden quedar vacios", "Atención...", JOptionPane.WARNING_MESSAGE);
            jTFNombre.requestFocus();
            return;
        }
        if(18>=Integer.parseInt(jSEdad.getValue().toString())){
            JOptionPane.showMessageDialog(  this, "La edad debe ser mayor a 18 años", "Atención...", JOptionPane.WARNING_MESSAGE);
            jSEdad.requestFocus();
            return;
        }
        if(jCBSexo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(  this, "Seleccione el sexo M o F", "Atención...", JOptionPane.WARNING_MESSAGE);
            jSEdad.requestFocus();
            return;
        }
        else {
            JOptionPane.showMessageDialog(this, "Datos guardados correctamente.", 
                                          "Validación Exitosa", JOptionPane.INFORMATION_MESSAGE);
        }
        //Acá se debe de concatenar los datos y cargar en los modelos para mostrar en las listas.
        //Ir a las últimas líneas del código para ver lo importado sobre los modelos.
        if(jRBEnfermeria.isSelected()){
            modeloEnfermeria.addElement(jTFNombre.getText()+" "+jSEdad.getValue().toString()+" "+jCBSexo.getSelectedItem().toString());
            jCBEnfermeria.setModel(modeloEnfermeria);  
        }
        if(jRBNutricion.isSelected()){
            modeloNutricion.addElement(jTFNombre.getText()+" "+jSEdad.getValue().toString()+" "+jCBSexo.getSelectedItem().toString());
            jLNutricion.setModel(modeloNutricion);
        }
        if(jRBFisioterapia.isSelected()){
            modeloFisioterapia.addElement(jTFNombre.getText()+" "+jSEdad.getValue().toString()+" "+jCBSexo.getSelectedItem().toString());
            jCBFisioterapia.setModel(modeloFisioterapia);  
        }
        if(jRBInformatica.isSelected()){
            modeloInformatica.addElement(jTFNombre.getText()+" "+jSEdad.getValue().toString()+" "+jCBSexo.getSelectedItem().toString());
            jLInformatica.setModel(modeloInformatica); 
        }
        //int totalAlumnos = 0;
        //int mascEnfermeria = 0, femEnfermeria = 0, mascNutricion = 0, femNutricion = 0, mascFisioterapia = 0, femFisioterapia = 0, mascInformatica = 0, femInformatica = 0;
        //Se debe de inicializar fuera de la clase (sino cada vez que se quiere inscribir a un alumno las variables se inicializan a 0).
        if(jRBEnfermeria.isSelected()){
            totalAlumnos++; //Contador del total de alumnos inscriptos.
            if (jCBSexo.getSelectedItem().toString().equals("M")) { //Verificación de si el alumno es Masculino para contar la cantidad.
                mascEnfermeria++;
            } 
            else { //Sino es M se debe de contar el Femenino.
                femEnfermeria++;
            }
        }
        if(jRBNutricion.isSelected()){
            totalAlumnos++;
            if (jCBSexo.getSelectedItem().toString().equals("M")) {
                mascNutricion++;
            } 
            else {
                femNutricion++;
            }
        }
        if(jRBFisioterapia.isSelected()){
            totalAlumnos++;
            if (jCBSexo.getSelectedItem().toString().equals("M")) {
                mascFisioterapia++;
            } 
            else {
                femFisioterapia++;
            }
        }
        if(jRBInformatica.isSelected()){
            totalAlumnos++;
            if (jCBSexo.getSelectedItem().toString().equals("M")) {
                mascInformatica++;
            } 
            else {
                femInformatica++;
            }
        }
        //Mostrar las cantidades en las etiquetas correspondientes.
        jLEnferFem.setText(String.valueOf(femEnfermeria));
        jLEnferMasc.setText(String.valueOf(mascEnfermeria));
        jLNutriFem.setText(String.valueOf(femNutricion));
        jLNutriMasc.setText(String.valueOf(mascNutricion));
        jLFisioFem.setText(String.valueOf(femFisioterapia));
        jLFisioMasc.setText(String.valueOf(mascFisioterapia));
        jLInfoFem.setText(String.valueOf(femInformatica));
        jLInfoMasc.setText(String.valueOf(mascInformatica));
        jSTotal.setValue(totalAlumnos);      
    }//GEN-LAST:event_jBInscribirActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        //Limpiar los campos de datos a ingresar.
        jTFNombre.setText(null);
        jTFApellido.setText(null);
        jTFTelefono.setText(null);
        jSEdad.setValue(18);
        bGCarreras.clearSelection();
        jCBSexo.setSelectedIndex(0);
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVaciarActionPerformed
            //Para las listas se deben de vaciar los modelos.
            modeloNutricion.clear();
            modeloInformatica.clear();
            //Para vaciar los ComboBox se debe de remover los items del CB.
            jCBEnfermeria.removeAllItems();
            jCBFisioterapia.removeAllItems();
            //Devolver las etiquetas y el slider a su valor inicial.
            jLEnferFem.setText("0");
            jLEnferMasc.setText("0");
            jLNutriFem.setText("0");
            jLNutriMasc.setText("0");
            jLFisioFem.setText("0");
            jLFisioMasc.setText("0");
            jLInfoFem.setText("0");
            jLInfoMasc.setText("0");
            jSTotal.setValue(0);
    }//GEN-LAST:event_jBVaciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP_II.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP_II.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP_II.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP_II.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP_II().setVisible(true);  
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGCarreras;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBVaciar;
    private javax.swing.JComboBox<String> jCBEnfermeria;
    private javax.swing.JComboBox<String> jCBFisioterapia;
    private javax.swing.JComboBox<String> jCBSexo;
    private javax.swing.JLabel jLBApellido;
    private javax.swing.JLabel jLBEnfermeria;
    private javax.swing.JLabel jLBFisioterapia;
    private javax.swing.JLabel jLBInformatica;
    private javax.swing.JLabel jLBNombre;
    private javax.swing.JLabel jLBNutricion;
    private javax.swing.JLabel jLBTelefono;
    private javax.swing.JLabel jLEdad;
    private javax.swing.JLabel jLEnferFem;
    private javax.swing.JLabel jLEnferMasc;
    private javax.swing.JLabel jLFisioFem;
    private javax.swing.JLabel jLFisioMasc;
    private javax.swing.JLabel jLInfoFem;
    private javax.swing.JLabel jLInfoMasc;
    private javax.swing.JList<String> jLInformatica;
    private javax.swing.JLabel jLNutriFem;
    private javax.swing.JLabel jLNutriMasc;
    private javax.swing.JList<String> jLNutricion;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JPanel jPCantidad;
    private javax.swing.JPanel jPCarreras;
    private javax.swing.JPanel jPDetalleInscripcion;
    private javax.swing.JPanel jPRegistrar;
    private javax.swing.JRadioButton jRBEnfermeria;
    private javax.swing.JRadioButton jRBFisioterapia;
    private javax.swing.JRadioButton jRBInformatica;
    private javax.swing.JRadioButton jRBNutricion;
    private javax.swing.JSpinner jSEdad;
    private javax.swing.JScrollPane jSPInformatica;
    private javax.swing.JScrollPane jSPNutricion;
    private javax.swing.JSlider jSTotal;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables
    //No sé que se hace acá, falte a clases ese día.
    DefaultComboBoxModel modeloEnfermeria = new DefaultComboBoxModel();
    DefaultListModel modeloNutricion = new DefaultListModel();
    DefaultComboBoxModel modeloFisioterapia = new DefaultComboBoxModel();
    DefaultListModel modeloInformatica = new DefaultListModel();
}