/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segunda_leng2.pkg5989216;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Montse Brizuela
 */
public class Final extends javax.swing.JFrame {

    private int Cont;
    private int Credi;
    private int Chec;
    private int Efec;
    private int ContF;
    private int CheM;
    private int TCONTandEfec;
    private int TCREDIandCHE;
    private int TGLOBAL;

    /**
     * Creates new form Final
     */
    public Final() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLVentaContado = new javax.swing.JLabel();
        jLCantPagadosEfectivo = new javax.swing.JLabel();
        jLtotalContadoEfectivo = new javax.swing.JLabel();
        jLVentaCredito = new javax.swing.JLabel();
        jLContadoMujer = new javax.swing.JLabel();
        jBconcretar = new javax.swing.JButton();
        jLChequeHombre = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCcrediCheque = new javax.swing.JComboBox<>();
        jBlimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JTcedula = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTapellido = new javax.swing.JTextField();
        jCsexo = new javax.swing.JComboBox<>();
        jSedad = new javax.swing.JSpinner();
        jTvalorTotal = new javax.swing.JTextField();
        jRcontado = new javax.swing.JRadioButton();
        jRcredito = new javax.swing.JRadioButton();
        jRcheque = new javax.swing.JRadioButton();
        jRefectivo = new javax.swing.JRadioButton();
        jStotal = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLcontadoEfectivo = new javax.swing.JList<>();
        jLtotalCreditoCheque = new javax.swing.JLabel();
        jLtotalAcumuladoCheque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLVentaContado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLVentaContado.setText("0");
        jLVentaContado.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Ventas Contado"));
        jLVentaContado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLCantPagadosEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLCantPagadosEfectivo.setText("0");
        jLCantPagadosEfectivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Pagos en Efectivo"));
        jLCantPagadosEfectivo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLtotalContadoEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLtotalContadoEfectivo.setText("0");
        jLtotalContadoEfectivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Ventas Contado / Efectivo"));
        jLtotalContadoEfectivo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLVentaCredito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLVentaCredito.setText("0");
        jLVentaCredito.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Ventas Credito"));
        jLVentaCredito.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLContadoMujer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLContadoMujer.setText("0");
        jLContadoMujer.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Ventas Contado / Mujeres"));
        jLContadoMujer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jBconcretar.setBackground(new java.awt.Color(204, 0, 204));
        jBconcretar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBconcretar.setText("Concretar Venta");
        jBconcretar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconcretarActionPerformed(evt);
            }
        });

        jLChequeHombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLChequeHombre.setText("0");
        jLChequeHombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Total de Ventas Cheque / Hombres"));
        jLChequeHombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jBcancelar.setBackground(new java.awt.Color(204, 0, 204));
        jBcancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBcancelar.setText("Cancelar Venta");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes con Ventas Crédito y Cheque", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jCcrediCheque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jScrollPane1.setViewportView(jCcrediCheque);

        jBlimpiar.setBackground(new java.awt.Color(204, 0, 204));
        jBlimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBlimpiar.setText("Limpiar Datos");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Showcard Gothic", 0, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cedula");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sexo");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Condicion de Venta");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Valor Total de Venta");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Forma de Pago");

        JTcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcedulaActionPerformed(evt);
            }
        });
        JTcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTcedulaKeyTyped(evt);
            }
        });

        jTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnombreKeyTyped(evt);
            }
        });

        jTapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTapellidoKeyTyped(evt);
            }
        });

        jCsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "M", "F" }));

        jSedad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 150, 1));

        jTvalorTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTvalorTotalKeyTyped(evt);
            }
        });

        buttonGroup1.add(jRcontado);
        jRcontado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRcontado.setText("Contado");

        buttonGroup1.add(jRcredito);
        jRcredito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRcredito.setText("Crédito");

        buttonGroup2.add(jRcheque);
        jRcheque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRcheque.setText("Cheque");

        buttonGroup2.add(jRefectivo);
        jRefectivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRefectivo.setText("Efectivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTapellido)
                                    .addComponent(jTnombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTcedula, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSedad)
                                    .addComponent(jCsexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addComponent(jRcheque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRefectivo)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRcontado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRcredito, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jTvalorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jCsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jRcontado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jRcredito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTvalorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRcheque)
                            .addComponent(jRefectivo))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jStotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jStotal.setMajorTickSpacing(10);
        jStotal.setMaximum(200);
        jStotal.setMinorTickSpacing(10);
        jStotal.setPaintLabels(true);
        jStotal.setPaintTicks(true);
        jStotal.setValue(0);
        jStotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total de Clientes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes con Ventas Contado y Efectivo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP)));

        jLcontadoEfectivo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jLcontadoEfectivo);

        jScrollPane2.setViewportView(jScrollPane3);

        jLtotalCreditoCheque.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLtotalCreditoCheque.setText("0");
        jLtotalCreditoCheque.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Ventas Crédito / Cheque"));
        jLtotalCreditoCheque.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLtotalAcumuladoCheque.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLtotalAcumuladoCheque.setText("0");
        jLtotalAcumuladoCheque.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Acumulado en Cheques"));
        jLtotalAcumuladoCheque.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLtotalAcumuladoCheque, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jLtotalCreditoCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLtotalContadoEfectivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLCantPagadosEfectivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBconcretar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBlimpiar))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLChequeHombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLContadoMujer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLVentaCredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLVentaContado, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLVentaContado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jLVentaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBconcretar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLtotalCreditoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLContadoMujer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLtotalContadoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLtotalAcumuladoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLCantPagadosEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLChequeHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStotal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBconcretarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconcretarActionPerformed
        if (JTcedula.getText ().isEmpty () == true)
        {
            JOptionPane.showMessageDialog (this, "El campo cedula no puede estar vacio", "ERROR", HEIGHT);
            JTcedula.requestFocus ();
        } else if (jTnombre.getText ().isEmpty () == true)
        {
            JOptionPane.showMessageDialog (this, "El campo nombre no puede estar vacio", "ERROR", HEIGHT);
            jTnombre.requestFocus ();
        } else if (jTapellido.getText ().isEmpty () == true)
        {
            JOptionPane.showMessageDialog (this, "El campo apellido no puede estar vacio", "ERROR", HEIGHT);
            jTapellido.requestFocus ();
        } else if (jTvalorTotal.getText ().isEmpty () == true)
        {
            JOptionPane.showMessageDialog (this, "El campo Valor Total no puede estar vacio", "ERROR", HEIGHT);
            jTvalorTotal.requestFocus ();
        } else if (Integer.valueOf (jSedad.getValue ().toString ()) <= 18)
        {
            JOptionPane.showMessageDialog (this, "Debe ser mayor de edad", "ERROR", HEIGHT);
            jSedad.requestFocus ();

        } else if (jCsexo.getSelectedItem ().equals ("Seleccione..."))
        {
            JOptionPane.showMessageDialog (this, "Defina el sexo", "ERROR", HEIGHT);
        } else if (!jRcheque.isSelected () && !jRefectivo.isSelected ())
        {
            JOptionPane.showMessageDialog (this, "Seleccione un metodo de Pago", "ERROR", HEIGHT);
        }else if(!jRcontado.isSelected () && !jRcredito.isSelected ()){
            JOptionPane.showMessageDialog (this, "Seleccione una condición de Venta", "ERROR", HEIGHT);
        }else
        {
            carga ();
        }
    }//GEN-LAST:event_jBconcretarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        limpiar ();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        limpiar ();
        jCcrediCheque.removeAllItems ();
        DefaultListModel Clear = new DefaultListModel();
        jLcontadoEfectivo.setModel (Clear);
        jLtotalCreditoCheque.setText ("0");
        jLtotalAcumuladoCheque.setText ("0");
        jLtotalContadoEfectivo.setText ("0");
        jLCantPagadosEfectivo.setText ("0");
        jLVentaContado.setText ("0");
        jLVentaCredito.setText ("0");
        jLContadoMujer.setText ("0");
        jLChequeHombre.setText ("0");
        jStotal.setValue (0);

        
        Cont = 0;

        Credi = 0;

        Chec = 0;

        Efec = 0;

        ContF = 0;

        CheM = 0;

        TCONTandEfec = 0;

        TCREDIandCHE = 0;

        TGLOBAL = 0;
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void JTcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcedulaActionPerformed

    private void JTcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTcedulaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_JTcedulaKeyTyped

    private void jTnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombreKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A'| c>'Z')) evt.consume();
    }//GEN-LAST:event_jTnombreKeyTyped

    private void jTapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTapellidoKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A'| c>'Z')) evt.consume();
    }//GEN-LAST:event_jTapellidoKeyTyped

    private void jTvalorTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTvalorTotalKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_jTvalorTotalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTcedula;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBconcretar;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JComboBox<String> jCcrediCheque;
    private javax.swing.JComboBox<String> jCsexo;
    private javax.swing.JLabel jLCantPagadosEfectivo;
    private javax.swing.JLabel jLChequeHombre;
    private javax.swing.JLabel jLContadoMujer;
    private javax.swing.JLabel jLVentaContado;
    private javax.swing.JLabel jLVentaCredito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jLcontadoEfectivo;
    private javax.swing.JLabel jLtotalAcumuladoCheque;
    private javax.swing.JLabel jLtotalContadoEfectivo;
    private javax.swing.JLabel jLtotalCreditoCheque;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRcheque;
    private javax.swing.JRadioButton jRcontado;
    private javax.swing.JRadioButton jRcredito;
    private javax.swing.JRadioButton jRefectivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSedad;
    private javax.swing.JSlider jStotal;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTvalorTotal;
    // End of variables declaration//GEN-END:variables

   

      DefaultComboBoxModel CreditoCheque = new DefaultComboBoxModel ();

      DefaultListModel ContadoEfectivo = new DefaultListModel ();
    
    private void carga() {
        String Cliente, Nombre, Apellido, Sexo;
	    Nombre = jTnombre.getText ();
	    Apellido = jTapellido.getText ();
	    Sexo = String.valueOf (jCsexo.getSelectedItem ());
	    Cliente = Nombre + " » " + Apellido + " » " + Sexo;
            
            if (jRcredito.isSelected () && jRcheque.isSelected ())
	    {
		  CreditoCheque.addElement (Cliente);
		  jCcrediCheque.setModel (CreditoCheque);
		  TCREDIandCHE++;

	    } else if (jRcontado.isSelected () && jRefectivo.isSelected ())
	    {
		  ContadoEfectivo.addElement (Cliente);
		  jLcontadoEfectivo.setModel (ContadoEfectivo);
		  TCONTandEfec++;

	    }
	    if (jRcontado.isSelected ())
	    {
		  Cont++;
		  if (jCsexo.getSelectedItem ().equals ("F"))
		  {
			ContF++;
		  }
	    }
	    if (jRcheque.isSelected ())
	    {
		  Chec++;
		  if (jCsexo.getSelectedItem ().equals ("M"))
		  {
			CheM++;
		  }
	    }
	    if (jRcredito.isSelected ())
	    {
		  Credi++;
	    }
	    if (jRefectivo.isSelected ())
	    {
		  Efec++;
	    }

	    jLtotalContadoEfectivo.setText (String.valueOf (TCONTandEfec));
	    jLtotalCreditoCheque.setText (String.valueOf (TCREDIandCHE));
	    jLVentaContado.setText (String.valueOf (Cont));
	    jLContadoMujer.setText (String.valueOf (ContF));
	    jLtotalAcumuladoCheque.setText (String.valueOf (Chec));
	    jLChequeHombre.setText (String.valueOf (CheM));
	    jLVentaCredito.setText (String.valueOf (Credi));
	    jLCantPagadosEfectivo.setText (String.valueOf (Efec));

	    TGLOBAL = Cont + Credi;
	    jStotal.setValue (TGLOBAL);
    }
    private void limpiar() {
        JTcedula.setText (null);
	    jTnombre.setText (null);
	    jTapellido.setText (null);
	    jSedad.setValue (1);
	    jCsexo.setSelectedItem ("Seleccione...");
	    buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
	    jTvalorTotal.setText (null);
    }
}
